print('           /|')
print('          / |')
print('         /  |')
print('        /   |')
print('       /    |')
print('      /     |')
print('     /      |')
print('    /       |')
print('   /________|')


print('        ______')
print('     ''/        \'')
print('    ''/          \'')
print('   ''/            \'')
print('  ''/              \'')
print(' ''|'               |'')
print(' ''|'               |'')
print(' ''|'               |'')
print('     ''\        /'')
print('      ''\      /'')
print('       ______')
